cluster task to run iperf

diff --git a/.taskfiles/Cluster/Tasks.yml b/.taskfiles/Cluster/Tasks.yml
--- a/.taskfiles/Cluster/Tasks.yml
+++ b/.taskfiles/Cluster/Tasks.yml
@@ -1,6 +1,9 @@
 ---
 version: "3"
 
+vars:
+  TIMENOW:
+    sh: date +%Y%m%d-%H%M%S
 tasks:
 
   verify:
@@ -49,3 +52,66 @@ tasks:
     cmds:
       - kubectl get hr --all-namespaces | grep False | awk '{print $2, $1}' | xargs -l bash -c 'flux suspend hr $0 -n $1'
       - kubectl get hr --all-namespaces | grep False | awk '{print $2, $1}' | xargs -l bash -c 'flux resume hr $0 -n $1'
+
+  wait-pod-pending:
+    aliases: [waitp]
+    internal: true
+    desc: Wait for a job's pod to change its status to pending
+    vars:
+      NAME: '{{ or .NAME (fail "Missing `NAME` environment variable!") }}'
+      NS: '{{ .NS | default "default" }}'
+    cmds:
+      - until [[ $(kubectl -n "{{.NS}}" get pod "{{.NAME}}" -o jsonpath='{.items[*].status.phase}') == "Pending" ]]; do sleep 1; done
+
+  wait-pod-running:
+    aliases: [waitp]
+    internal: true
+    desc: Wait for a job's pod to change its status to pending
+    vars:
+      NAME: '{{ or .NAME (fail "Missing `NAME` environment variable!") }}'
+      NS: '{{ .NS | default "default" }}'
+    cmds:
+      - until [[ $(kubectl -n "{{.NS}}" get pod "{{.NAME}}" -o jsonpath='{.items[*].status.phase}') == "Running" ]]; do sleep 1; done
+
+  wait-finish:
+    internal: true
+    desc: Wait for a job's pod to change its status to pending
+    vars:
+      NAME: '{{ or .NAME (fail "Missing `NAME` environment variable!") }}'
+      NS: '{{ .NS | default "default" }}'
+      # TYPE: '{{ .TYPE | default "job" }}'
+      # WAIT_ARGS: '{{.WAIT_ARGS | default "echo \"{{.NAME}} is still running, logs:\" && kubectl -n {{.NS}} logs {{.NAME}} --since 2s -f;"}}'
+    cmds:
+      - |-
+        until kubectl -n {{.NS}} wait {{.NAME}} --for condition=complete --timeout=2s; do
+          echo "{{.NAME}} is still running, logs:" && kubectl -n {{.NS}} logs {{.NAME}} --since 2s -f || true;
+        done
+
+  iperf2:
+    desc: Start a iperf2 server on node SERVER_NODE, and iperf2 client on node CLIENT_NODE, to benchmark network performance.
+    dir: "{{.ROOT_DIR}}/.taskfiles/Cluster/iperf2"
+    vars: &iperf2-vars
+      SERVER_NAME: &iperf2-server-name 'iperf2-server-{{- .TIMENOW -}}'
+      SERVER_NS: &iperf2-server-ns '{{ .SERVER_NS | default "default" }}'
+      CLIENT_NAME: &iperf2-client-name 'iperf2-client-{{- .TIMENOW -}}'
+      CLIENT_NS: &iperf2-client-ns '{{ .CLIENT_NS | default "default" }}'
+      CLUSTER_DOMAIN: '{{ .CLUSTER_DOMAIN | default "cluster.local" }}'
+      SERVER_PORT: '{{ .SERVER_PORT | default "5001" }}'
+      SERVER_NODE: '{{ or .SERVER_NODE (fail "Missing `SERVER_NODE` environment variable!") }}'
+      CLIENT_NODE: '{{ or .CLIENT_NODE (fail "Missing `CLIENT_NODE` environment variable!") }}'
+      SERVER_ARGS: '{{ .SERVER_ARGS | default "" }}'
+      CLIENT_ARGS: '{{ .CLIENT_ARGS | default "" }}'
+    env: *iperf2-vars
+    cmds:
+      - cat ./ServerJob.tmpl.yaml | envsubst | kubectl apply -f -
+      - defer: cat ./ServerJob.tmpl.yaml | envsubst | kubectl delete -f -
+      - task: wait-pod-running
+        vars:
+          NAME: '-l job-name={{.SERVER_NAME}}'
+          NS: '{{.SERVER_NS}}'
+      - cat ./ClientJob.tmpl.yaml | envsubst | kubectl apply -f -
+      - defer: cat ./ClientJob.tmpl.yaml | envsubst | kubectl delete -f -
+      - task: wait-finish
+        vars:
+          NAME: 'jobs/{{.CLIENT_NAME}}'
+          NS: '{{.CLIENT_NS}}'
